# Generated by Django 4.2.4 on 2023-08-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_alter_receipts_group_or_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='channel_and_group',
            field=models.ManyToManyField(blank=True, to='Models.groupandchennel', verbose_name='Группы и чаты пользователя'),
        ),
    ]
