# Generated by Django 4.2.4 on 2023-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_alter_user_channel_and_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='command_start',
            field=models.IntegerField(default=0, verbose_name='Сколько раз использовал комманду /start'),
        ),
    ]
