# Generated by Django 4.2.4 on 2023-08-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_product_max_summ_product_min_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='message/', verbose_name='Фотография к сообщению'),
        ),
    ]
